# Generated by Django 3.2.12 on 2022-04-29 14:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='../static/accounts/default_profile.jpg', upload_to='profile/'),
        ),
    ]
